config_version: 1
database:
  type: sqlite

  # typeをmysqlにしたときに必要な情報です
  address: 'localhost:3306'
  database: 'database_name'
  username: 'username'
  password: 'password'

prices:
  coal: 100
  raw-iron: 1000
  raw-copper: 1500
  raw-gold: 5000000
  lapis-lazuli: 1750
  redstone-dust: 2000
  diamond: 10000
