config_version: 1
database:
  type: sqlite

  # typeをmysqlにしたときに必要な情報です
  address: 'localhost:3306'
  database: 'database_name'
  username: 'username'
  password: 'password'

  master_bank_name: "master_bank"