name: Metaverseplugin
version: '${version}'
main: tech.inudev.metaverseplugin.Metaverseplugin
api-version: 1.18
authors: [ kumitatepazuru ]
description: めたばーすぷらぐいん（仮）
website: https://www.inu-dev.tech/
depend:
  - floodgate
  - Geyser-Spigot

commands:
  money:
    description: This is test money command
permissions:
  money:
    description: test money command permission
    default: true