name: Profundus
version: '${version}'
main: tech.inudev.profundus.Profundus
api-version: 1.18
authors: [ kumitatepazuru ]
description: めたばーすぷらぐいん（仮）
website: https://www.inu-dev.tech/
depend:
  - floodgate
  - Geyser-Spigot